### ISSUE TITLE
Can't find working travis

### ISSUE THREAD

**Issue by dacb** [EISy-as-Py/eisy#3]
It looks like you have all the files for travis CI but I couldn't find it on travis.  If you have this setup, go ahead and put a badge with a link to the travis page in your `/README.md` so that others can find it.  I also recommend setting up the coveralls.io stuff and badging that in your README.md as well.

**Comment by FencerDave** [comment]
I've been trying over the weekend but I can't get Travis to work... 
I set it up following their installation guide and it's located here: https://travis-ci.org/EISy-as-Py/EISy_as_Py/

I ran it a few times and I have error reports, but so far I don't understand how it's supposed to be set up and function

**Comment by MariaPoliti** [comment]
Travis CI was set up for the eisy repository and badge can be found at the top of the README.md file
